migrate to gojmx
newrelic/nri-kafka pull request #163
Opened 2022-03-08 10:45 UTC by cristianciutea

2022-03-14 17:10 UTC, roobre requested changes
Left a few nits here and there. However, the untested singleton dispatcher a blocker for me in order to merge this. I'd love if we could rewrite it into something less global and have a small test for it.

2022-03-14 17:10 UTC, roobre commented on src/connection/jmx.go
> +	}()
I think I get what you want to achieve here (release after this func is called if there's an error) but I think doing it this way is not very intuitive for the reader.

Is there a different way in which we could do this? e.g. locking the semaphore after we check that `gojmx.NewClient` returns successfully?

2022-03-18 13:49 UTC, roobre approved these changes
Unblocking this now, but I'd love if someone else on @newrelic/coreint could give it some 👀 as well

2022-03-21 14:20 UTC, alvarocabanas approved these changes
Nice work! I just put a couple of nits just to separate a bit the concerns, but completely optional.

2022-03-21 14:20 UTC, alvarocabanas commented on src/client/producer_consumer_collection.go
>  			}
I would also move this and in the producerWorker bellow Jmx bellow to a private getConsumerJMXConnection or ConsumerJMXConnect function, just to have it more readable.

2022-03-22 13:26 UTC, cristianciutea commented
> Left a few nits here and there. However, the untested singleton dispatcher a blocker for me in order to merge this. I'd love if we could rewrite it into something less global and have a small test for it.

I've removed the global singleton of connection provider and added tests for it.
Also did some refactor to address other comments.

2022-03-29 08:10 UTC, roobre commented
LGTM, thanks for taking care of this!

2022-03-29 08:10 UTC, merged